# Generated by Django 2.2.12 on 2020-07-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USStates',
            new_name='USState',
        ),
        migrations.CreateModel(
            name='Hometown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.USState')),
            ],
        ),
    ]
