# Generated by Django 2.2.12 on 2020-07-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200705_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hometown',
            new_name='Location',
        ),
    ]
