# Generated by Django 2.2.12 on 2020-07-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_contactmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
