# Generated by Django 2.2.12 on 2020-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200702_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
    ]
