# Generated by Django 2.2.12 on 2020-05-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('full_name', models.CharField(max_length=60)),
                ('hometown', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=75)),
                ('changed_major', models.CharField(max_length=10)),
                ('original_major', models.CharField(max_length=75)),
                ('leadership', models.TextField(max_length=255)),
                ('grad_date', models.CharField(max_length=30)),
                ('current_occupation', models.TextField(max_length=255)),
                ('career_long_term', models.TextField(max_length=255)),
                ('expected_career', models.TextField(max_length=255)),
                ('career_path', models.CharField(max_length=50)),
                ('favorites', models.TextField(max_length=255)),
                ('mentorship_selections', models.CharField(max_length=100)),
                ('conference_location', models.CharField(max_length=100)),
                ('conference_topics', models.TextField(max_length=255)),
                ('contact_method', models.CharField(max_length=100)),
            ],
        ),
    ]
