# Generated by Django 2.2.12 on 2020-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='conference_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='contact_method',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='hometown',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='mentorship_selections',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='residence',
            field=models.CharField(max_length=200),
        ),
    ]
