# Generated by Django 2.2.12 on 2020-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200526_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='degree',
            field=models.CharField(max_length=150),
        ),
    ]
