# Generated by Django 2.2.12 on 2020-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200526_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='grad_date',
            field=models.CharField(max_length=60),
        ),
    ]
