# Generated by Django 2.2.12 on 2020-07-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alumnidata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniData',
        ),
    ]
