# Generated by Django 2.2.12 on 2020-07-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_degree_involvementorleadershipposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.JobSector')),
            ],
        ),
    ]
