# Generated by Django 2.2.12 on 2020-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_jobsector_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
