# Generated by Django 2.2.12 on 2020-06-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
