# Generated by Django 2.2.12 on 2020-06-04 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_interaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
