# Generated by Django 2.2.12 on 2020-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_interaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
